    # H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:bookstoredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Configuration (Access at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# setting validate to match entities and tables
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#logging
logging.level.root=INFO
logging.level.com.bnppf.bookstore=DEBUG